import { detectLanguageKey, detectLanguage } from './languages.js';

// Mock/demo provider — no API key required. Deterministic checks so the app is useful out of the box.

function scanFile(langKey, code) {
  if (!code) return [];
  const issues = [];
  const lines = code.split('\n');
  const indent = new Set();
  for (const l of lines) {
    const m = l.match(/^[ \t]+/);
    if (m) indent.add(m[0][0]);
  }
  if (indent.size > 1) {
    issues.push({ id: 'mixed-indent', severity: 'info', line: 1, message: 'Mixed tab/space indentation — normalize to spaces (2 or 4).' });
  }
  lines.forEach((line, i) => {
    if (line.length > 160) {
      issues.push({ id: 'long-line', severity: 'info', line: i + 1, message: `Line ${i + 1} is ${line.length} chars — consider splitting.` });
    }
    if (/^\s*todo\s*:/i.test(line) || /\/\/\s*todo/i.test(line) || /#\s*todo/i.test(line)) {
      issues.push({ id: 'todo', severity: 'info', line: i + 1, message: 'TODO/FIXME found.' });
    }
    if (/[ \t]+$/.test(line) && line.trim().length > 0) {
      issues.push({ id: 'trailing-ws', severity: 'info', line: i + 1, message: `Trailing whitespace on line ${i + 1}.` });
    }
  });
  return issues;
}

function languageNameToKey(name) {
  const n = (name || '').toLowerCase();
  if (/javascript|js|node/i.test(n)) return 'js';
  if (/typescript|ts/i.test(n)) return 'ts';
  if (/python|py/i.test(n)) return 'py';
  if (/java\b/.test(n)) return 'java';
  if (/go\b|golang/.test(n)) return 'go';
  if (/rust|rs\b/.test(n)) return 'rust';
  return 'js';
}

export default {
  isMock: true,
  name: 'mock',

  async chat(messages) {
    const last = messages[messages.length - 1]?.content || '';
    const text = last.toLowerCase();
    let reply = "Got it. I can organize your project, review & fix code, generate code from plain language, or deploy it. Upload a zip or type what you want to build.";
    if (/(hi|hello|hey)\b/.test(text)) reply = "Hey! I'm VibeDev. Drop a zip, tell me what to build, and I'll organize, fix, generate, and deploy.";
    else if (/organiz/.test(text)) reply = "I can auto-organize any project into src/, tests/, docs/, assets/. Upload a zip and I'll handle it.";
    else if (/deploy/.test(text)) reply = "Ready to deploy! I can push to GitHub and spin up free hosting (Render / GitHub Pages / Netlify).";
    else if (/fix|bug|error/.test(text)) reply = "I'll scan your code for bugs and style issues, then apply fixes automatically.";
    else if (/generate|build|make|create/.test(text)) reply = "Tell me what you want in plain English and I'll write the code.";
    else if (/github/.test(text)) reply = "Connect via OAuth or a Personal Access Token. I can create repos, commit, and push.";
    return { role: 'assistant', content: reply, mock: true };
  },

  async reviewCode(files) {
    const results = [];
    let score = 100;
    for (const file of files || []) {
      const langKey = detectLanguageKey(file.path);
      const issues = scanFile(langKey, file.content);
      const weight = { error: 8, warn: 4, info: 1 };
      for (const i of issues) score = Math.max(0, score - (weight[i.severity] || 1));
      results.push({ path: file.path, language: detectLanguage(file.path), issues });
    }
    return { score, files: results };
  },

  async fixCode(files) {
    const fixed = [];
    for (const file of files || []) {
      let code = file.content || '';
      code = code.split('\n').map(l => l.replace(/[ \t]+$/, '')).join('\n');
      code = code.replace(/^\uFEFF/, '');
      if (code && !code.endsWith('\n')) code += '\n';
      fixed.push({ path: file.path, content: code, changed: code !== (file.content || '') });
    }
    return { fixed };
  },

  async generateCode(description, { language = 'Python' } = {}) {
    const lk = languageNameToKey(language);
    const templates = {
      py: `import sys\n\n# ${description}\ndef main():\n    print("Generated by VibeDev")\n\nif __name__ == "__main__":\n    main()\n`,
      js: `// ${description}\n'use strict';\nfunction main() {\n  console.log("Generated by VibeDev");\n}\nmain();\n`,
      ts: `// ${description}\nfunction main(): void {\n  console.log("Generated by VibeDev");\n}\nmain();\n`,
      default: `// ${description}\nconsole.log("Hello from VibeDev!");\n`
    };
    const code = templates[lk] || templates.default;
    return {
      language: detectLanguage('.' + (lk === 'plain' ? 'txt' : lk)),
      fileName: lk === 'py' ? 'main.py' : lk === 'ts' ? 'index.ts' : 'index.js',
      code,
      explanation: `Generated a starter ${language} program for: ${description}`
    };
  },

  async organizeFiles(files) {
    const src = [], tests = [], docs = [], assets = [], config = [], root = [];
    for (const f of files || []) {
      const p = f.path.toLowerCase();
      if (/(test|spec)\.|__tests__|tests?\//.test(p)) tests.push(f.path);
      else if (/\.(md|rst|txt)$/.test(p) && /\b(readme|docs?|changelog|license)\b/.test(p)) docs.push(f.path);
      else if (/\.(png|jpg|jpeg|gif|svg|ico|webp|woff2?|ttf)$/.test(p)) assets.push(f.path);
      else if (/\.(json|ya?ml|toml|ini|cfg|conf|env|gitignore|lock|dockerfile)$/.test(p)) config.push(f.path);
      else if (/\.(js|ts|py|java|go|rb|php|rs|jsx|tsx|vue|svelte|html|css)$/.test(p)) src.push(f.path);
      else root.push(f.path);
    }
    return {
      plan: [
        { folder: 'src/', files: src, reason: 'Source code belongs in src/.' },
        { folder: 'tests/', files: tests, reason: 'Test/spec files under tests/.' },
        { folder: 'docs/', files: docs, reason: 'Documentation under docs/.' },
        { folder: 'assets/', files: assets, reason: 'Static assets under assets/.' },
        { folder: '(root config)', files: config, reason: 'Config files stay at root.' },
        { folder: '(root)', files: root, reason: 'Entry points and dotfiles at root.' }
      ],
      stats: { total: (files || []).length, src: src.length, tests: tests.length, docs: docs.length, assets: assets.length, config: config.length, root: root.length }
    };
  },

  async addMissingCode(project) {
    const missing = [];
    const has = p => project.files.some(f => f.path.toLowerCase() === p.toLowerCase());
    const name = project.name || 'my-project';
    if (!has('README.md')) {
      missing.push({
        path: 'README.md',
        reason: 'No README found.',
        content: `# ${name}\n\nBuilt with **VibeDev**.\n\n## Getting Started\n1. Install dependencies\n2. Run the project\n`
      });
    }
    if (!has('.gitignore')) {
      missing.push({
        path: '.gitignore',
        reason: 'No .gitignore found.',
        content: 'node_modules/\ndist/\nbuild/\n.env\ncoverage/\nvenv/\n__pycache__/\n'
      });
    }
    return { added: missing };
  }
};
